name:     "ElementsMultiHighlight"

exports:  "ElementsMultiHighlight.js"

author:   "subhaze"

category: "Effects"

tags:     "[navigation, tween, element, effects]"

demo:     "http://www.jsfiddle.net/subhaze/CZDfM/"

current: "v1.1"

sources:
  - "Source/Elements.MultiHighlight.js"