name:     "ElementsMultiHighlight"

exports:  "ElementsMultiHighlight.js"

author:   "subhaze"

category: "Effects"

tags:     "[navigation, tween, element, effects]"

demo:     "https://github.com/subhaze/mootools-elements-multihighlight/blob/master/Source/Elements.MultiHighlight.js"

current: "v1.1"

sources:
  - "Source/Elements.MultiHighlight.js"